<a href="https://colab.research.google.com/github/Farrzz98/myproject2/blob/main/Supervised_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# SUPERVISED MACHINE LEARNING
# Simple Linear Regression
# First Project : Predict Student Marks On The Basis Of Number Of Hours Studied
# Linear regression is a basic and commonly used type of predictive analysis.
# Linear regression is an attempt to model the relationship between two variables by fitting
# a linear equation to observed data

In [ ]:
# Step 1 : Data Gathering
# Load The Dataset

import pandas as pd
data = pd.read_csv('https://trello-attachments.s3.amazonaws.com/6062c6af283e86843a32b025/60e266a5cf1b3460fe131e0c/cb6cbe6b2618beadbe806a60de87b61a/Grade_Set_1.csv')
data

Hours_Studied  Test_Grade Status Result
0              2          57   fail      D
1              3          66   fail      D
2              4          73   pass      C
3              5          76   pass      C
4              6          79   pass      C
5              7          81   pass      B
6              8          90   pass      B
7              9          96   pass      A
8             10         100   pass      A

In [ ]:
# Basic Data Exploration
data.columns

Index(['Hours_Studied', 'Test_Grade', 'Status', 'Result'], dtype='object')

In [ ]:
data.shape

(9, 4)

In [ ]:
# Step 2 : Data Preparation
# 1.) Check For Missing Values
# 2.) Convert Categorical Values / Non Numerical Into Numerical Features
# 3.) Normalization
# 4.) Select Dependent And Independent Variable

In [ ]:
data.isnull().sum()

Hours_Studied    0
Test_Grade       0
Status           0
Result           0
dtype: int64

In [ ]:
# Convert categorical into numerical features
from sklearn.preprocessing import LabelBinarizer
# create an object for LabelBinarizer Class
lb = LabelBinarizer()
data.Status = lb.fit_transform(data.Status)

In [ ]:
data

Hours_Studied  Test_Grade  Status Result
0              2          57       0      D
1              3          66       0      D
2              4          73       1      C
3              5          76       1      C
4              6          79       1      C
5              7          81       1      B
6              8          90       1      B
7              9          96       1      A
8             10         100       1      A

In [ ]:
# Normalization
# Changing the scale of a mutltiple variable into a same range [0-1]
# Why normalization is necessary for machine learning ?
# MIN-MAX Scaling
# Xnorm = (X - XMIN) / (XMAX - XMIN)
# X = 100
# XMIN = 57
# XMAX = 100

In [ ]:
# Select Dependent And Independent Variable
import numpy as np
X = data.Hours_Studied.values
X = X.reshape(9,1)

In [ ]:
X

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
Y = data.Test_Grade.values
Y

array([ 57,  66,  73,  76,  79,  81,  90,  96, 100])

In [ ]:
# Step 3 : Train The Dataset
# Choose a model --> Simple Linear Regression
# Y` = mX + c
# where ,
#         Y` --> Predicted Values
#         m  --> slope/coefficient [Change in the value of Y w.r.t  X]
#         X  --> Independent Variable
#         c  --> intercept [Value of Y when X is zero]

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [ ]:
lin_reg.fit(X,Y)

LinearRegression()

In [ ]:
# Print Predicted Values
predicted_values = lin_reg.predict(X)
predicted_values

array([59.71111111, 64.72777778, 69.74444444, 74.76111111, 79.77777778,
       84.79444444, 89.81111111, 94.82777778, 99.84444444])

In [ ]:
data['predicted_values'] = predicted_values
data[['predicted_values','Test_Grade']]

predicted_values  Test_Grade
0         59.711111          57
1         64.727778          66
2         69.744444          73
3         74.761111          76
4         79.777778          79
5         84.794444          81
6         89.811111          90
7         94.827778          96
8         99.844444         100

In [ ]:
# Evaluate Model Performance
from sklearn.metrics import r2_score
accuracy = r2_score(Y,predicted_values)
print("Accuracy :",accuracy)

Accuracy : 0.9757431074095347


In [ ]:
# Final Prediction
hrs = float(input('Enter Number Of Hours Studied : '))
marks = lin_reg.predict([[hrs]])
print('Student who studies for',hrs,'hours will going to score',marks,'marks.')

Enter Number Of Hours Studied : 6
Student who studies for 6.0 hours will going to score [79.77777778] marks.
